server:
  port: 8081

spring:
  http:
    encoding:
      charset: utf-8
  #添加springboot静态资源映射
#  resources:
#    static-locations: ["classpath:/META-INF/resources","classpath:/resources","classpath:/static","classpath:/public"]


#humen:
#  name: pigletO
#  sex: 男
#  age: 18
#  parent: {father: "老爸",mather: "老妈"}
##  hobby: ["足球","排球","篮球"]
#  hobby:
#    - "足球"
#    - "篮球"
#    - "排球"
#  type: yaml
#  pet:
#    name: "熊熊"
#    sex: "雄"


---
#spring:
#     mvc:
#       formcontent:
#         putfilter:
#           enabled
