server:
  port: 8081

spring:
  http:
    encoding:
      charset: utf-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


#humen:
#  name: pigletO
#  sex: 男
#  age: 18
#  parent: {father: "老爸",mather: "老妈"}
##  hobby: ["足球","排球","篮球"]
#  hobby:
#    - "足球"
#    - "篮球"
#    - "排球"
#  type: yaml
#  pet:
#    name: "熊熊"
#    sex: "雄"


---
spring:
     mvc:
       formcontent:
         putfilter:
           enabled
