server:
  port: 8081
#  servlet:
#    context-path: /springBootDemo


spring:
  http:
    encoding:
      charset: utf-8
  #修改国际化配置文件读取路径
  messages:
    basename: i18n.login
  #禁用thymeleaf模板引擎的缓存功能
  thymeleaf:
    cache: false
#    webMVC默认的输入的时间格式为yyyy/MM/dd
  mvc:
    date-format: yyyy-MM-dd
#   激活指定配置
  profiles:
    active: dev
#  mvc:
#    static-path-pattern: classpath:/static/**

#添加springboot静态资源映射
#  resources:
#    static-locations: ["classpath:/META-INF/resources","classpath:/resources","classpath:/static","classpath:/public"]

#humen:
#  name: pigletO
#  sex: 男
#  age: 18
#  parent: {father: "老爸",mather: "老妈"}
##  hobby: ["足球","排球","篮球"]
#  hobby:
#    - "足球"
#    - "篮球"
#    - "排球"
#  type: yaml
#  pet:
#    name: "熊熊"
#    sex: "雄"
---
#spring:
#     mvc:
#       formcontent:
#         putfilter:
#           enabled

---
spring:
     profiles: dev
server:
  port: 8088