server:
  port: 8081





spring:
  http:
    encoding:
      charset: utf-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

---
spring:
     mvc:
       formcontent:
         putfilter:
           enabled
